spring:
  security:
    oauth2:
      client:
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response



        registration:
          naver:
#            client-id: u0YS9v6FyHQr9kVrcU8h
            client-id: uvxeeIjVjXJ0T_7Q8Qr4 #hanh
#            client-secret: PN6i94vBpO
            client-secret: Y_Fu5r8Y1m #hanh
            redirect-uri: http://localhost:8080/login/oauth2/code/naver
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_post
            client-name: Naver
            scope:
              - name
              - email

  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: file:media/,classpath:/static

  datasource:
    url: jdbc:sqlite:db.sqlite
    driver-class-name: org.sqlite.JDBC
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.community.dialect.SQLiteDialect

jwt:
  secret: iAxixh53UL,u]Znp!=]>k#7z#T~x!ne%w2#p2qk+4yHne71-gLhP*q%Fm
